/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myminesweeper;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.stream.Stream;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.BevelBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author willi
 */
public class Board extends javax.swing.JFrame {

    // Internationalization
    private static final ResourceBundle languages = ResourceBundle.getBundle("resources/languages", Locale.forLanguageTag("en-US"));
    
    // Preferences
    private final Configuration configForm;
    private int _minesQty;
    private int _nRows;
    private int _nCols;
    private int _cellSize;
    private int _pointCost;
    
    // Mines
    private final String MENSAGEM_MINAS = languages.getString("REMAINING");
    private final String MENSAGEM_MINAS_MINI = languages.getString("REMAINING_MINI");
    private int remainingMines;
    
    // Gold Coins
    private final String MENSAGEM_COINS = languages.getString("GOLD_COINS");
    private final String MENSAGEM_COINS_MINI = languages.getString("GOLD_COINS_MINI");
    private int successfulGuesses = 0;
    private int goldCoins = 0;
    
    // Clock
    private final StopTimer relogio;
    
    // BoardMap
    private BoardMap boardMap;
    private boolean gameOver;
    private boolean gameStarted;
    private boolean primeiroClique;
    
    // BoardController
    private final BoardController controlador;
    private boolean running = false;
    
    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        configForm = new Configuration(this, true);
        initPreferences();
        this.remainingMines = _minesQty;
        this.gameOver = true;
        this.gameStarted = false;
        this.primeiroClique = true;
        relogio = new StopTimer(this.jlabTempo);
        this.controlador = new BoardController(this);
    }

    /**
     * @return the _pointCost
     */
    public int getPointCost() {
        return _pointCost;
    }

     /**
     * @return the boardMap
     */
    public BoardMap getBoardMap() {
        return boardMap;
    }


    /**
     * @param pointCost the _pointCost to set
     */
    public void setPointCost(int pointCost) {
        _pointCost = pointCost;
    }
    
    public void addSuccesfulGuess(int val) {
        if (successfulGuesses + val == 10) {
            addGoldCoins(1);
            successfulGuesses = 0;
        } else {
            successfulGuesses += val;
        }
    }
    
    public void addGoldCoins(int val) {
        goldCoins += val;
        showGoldCoins();
    }
    
    private void showGoldCoins() {
        jlabGoldCoins.setText(MENSAGEM_COINS + String.valueOf(goldCoins));
    }
    
    public void setRemainingMines(boolean reduce) {
        if (reduce)
            jlabMinas.setText(jlabMinas.getName() + String.valueOf(--remainingMines));
        else 
            jlabMinas.setText(jlabMinas.getName() + String.valueOf(++remainingMines));
    }
    
    public void setGameOver(boolean val) {
        this.gameOver = val;
        if (val) {
            relogio.parar();
        }
    }
    
    public boolean isGameOn() {
        return !this.gameOver && this.gameStarted;
    }
    
    public boolean isGameOver() {
        return this.gameOver;
    }
    
    public boolean hasGameStarted() {
        return this.gameStarted;
    }
    
    public boolean isFirstClick() {
        return this.primeiroClique;
    }
    
    public void setFirstClick(boolean val) {
        this.primeiroClique = val;
    }
    
    public void setGameStarted(boolean val) {
        this.gameStarted = val;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanMineField = new javax.swing.JPanel();
        jpanStatusBar = new javax.swing.JPanel();
        jlabMinas = new javax.swing.JLabel();
        jlabGoldCoins = new javax.swing.JLabel();
        jlabTempo = new javax.swing.JLabel();
        jmnbMenu = new javax.swing.JMenuBar();
        jmnJogo = new javax.swing.JMenu();
        jmniNovo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jsSeparador1 = new javax.swing.JPopupMenu.Separator();
        jmniSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(260, 290));
        setName("Board"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 450));
        setSize(new java.awt.Dimension(260, 290));

        jpanMineField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanMineField.setMinimumSize(new java.awt.Dimension(230, 230));
        jpanMineField.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanStatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jpanStatusBar.setFocusable(false);
        jpanStatusBar.setMinimumSize(new java.awt.Dimension(242, 30));
        jpanStatusBar.setPreferredSize(new java.awt.Dimension(777, 30));
        jpanStatusBar.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        jlabMinas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlabMinas.setText(languages.getString("REMAINING_START_MINI")); // NOI18N
        jlabMinas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        jlabMinas.setMinimumSize(new java.awt.Dimension(80, 30));
        jlabMinas.setName("Minas Restantes: "); // NOI18N
        jpanStatusBar.add(jlabMinas);

        jlabGoldCoins.setBackground(new java.awt.Color(153, 153, 153));
        jlabGoldCoins.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlabGoldCoins.setForeground(new java.awt.Color(255, 153, 51));
        jlabGoldCoins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabGoldCoins.setText(languages.getString("GOLD_COINS_START")); // NOI18N
        jlabGoldCoins.setMinimumSize(new java.awt.Dimension(80, 30));
        jpanStatusBar.add(jlabGoldCoins);

        jlabTempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlabTempo.setText(languages.getString("TIME_ELAPSED_START_MINI")); // NOI18N
        jlabTempo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jlabTempo.setMinimumSize(new java.awt.Dimension(80, 30));
        jlabTempo.setName("Tempo Transcorrido: "); // NOI18N
        jpanStatusBar.add(jlabTempo);

        jmnJogo.setText(languages.getString("GAME")); // NOI18N

        jmniNovo.setText(languages.getString("NEW")); // NOI18N
        jmniNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniNovoActionPerformed(evt);
            }
        });
        jmnJogo.add(jmniNovo);

        jMenuItem1.setText(languages.getString("CONFIGURATION")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmnJogo.add(jMenuItem1);
        jmnJogo.add(jsSeparador1);

        jmniSair.setText(languages.getString("EXIT")); // NOI18N
        jmniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniSairActionPerformed(evt);
            }
        });
        jmnJogo.add(jmniSair);

        jmnbMenu.add(jmnJogo);

        setJMenuBar(jmnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpanMineField, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanStatusBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpanMineField, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 496, Short.MAX_VALUE)
                    .addComponent(jpanStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmniSairActionPerformed

    private void jmniNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniNovoActionPerformed
        novoJogo();
    }//GEN-LAST:event_jmniNovoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        loadConfigForm();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void startNewGame() {
        
    }
    
    public void novoJogo() {
        clearBoard();
        if (hasGameStarted()) {
            setFirstClick(true);
            setGameStarted(false);
            restartGoldCoins();
        }
        iniciarJogo();
        relogio.reiniciar();
        restartMines();
        if (!running){
            controlador.start();
            running = true;
        }
    }
    
    private void initBoard() throws Exception {

        // Criação do BoardMap
        this.boardMap = new BoardMap();
        Cell cell;
        for (int i = 0; i < getNRows(); i++) {
            for (int j = 0; j < getNCols(); j++) {
                cell = new Cell(new Point(i, j));
                cell.setMyBoard(this);
                this.getBoardMap().put(cell.getPosition(), cell);
            }
        }
        
        // BoardMap
        // Conectando as células entre si pelo perímetro
        Point point = new Point();
        this.getBoardMap().forEach((p, c) -> {
            // Superior Esquerda
            point.setLocation(p.x -1, p.y - 1);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Superior
            point.setLocation(p.x, p.y - 1);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Superior Direita
            point.setLocation(p.x + 1, p.y - 1);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Direita
            point.setLocation(p.x + 1, p.y);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Inferior Direita
            point.setLocation(p.x + 1, p.y + 1);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Inferior
            point.setLocation(p.x, p.y + 1);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Inferior Esquerda
            point.setLocation(p.x - 1, p.y + 1);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
            // Esquerda
            point.setLocation(p.x - 1, p.y);
            if (getBoardMap().containsKey(point)) {
                c.getPerimeter().add(getBoardMap().get(point));
            }
        });
    }
    
//    private void checkBoard() {
//        // First, check if all mines were flagmarked successfully.
//        if (isGameOn()) {
//            if (getBoardMap().areAllMinesFlagged()) {
//                setGameOver(true);
//                getBoardMap().flagRemainingCells();
//                getBoardMap().revealAllCells();
//                if (showConfirmationMessage(languages.getString("CONGRATULATIONS"), null)) {
//                    novoJogo();
//                }
//            }
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Board().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel jlabGoldCoins;
    private javax.swing.JLabel jlabMinas;
    private javax.swing.JLabel jlabTempo;
    private javax.swing.JMenu jmnJogo;
    private javax.swing.JMenuBar jmnbMenu;
    private javax.swing.JMenuItem jmniNovo;
    private javax.swing.JMenuItem jmniSair;
    private javax.swing.JPanel jpanMineField;
    private javax.swing.JPanel jpanStatusBar;
    private javax.swing.JPopupMenu.Separator jsSeparador1;
    // End of variables declaration//GEN-END:variables

    private void iniciarJogo() {
        setGameOver(false);
        try {
            initBoard();        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        }
        
        // Redimensionamento
        Dimension frameSize = new Dimension(getCellSize() * getNRows() + 25, getCellSize() * getNCols() + 105);
        this.setSize(frameSize);
        
        // Através da BoardMap
        this.getBoardMap().forEach((p, c) -> {
            setInitialCellAtributes(c);
            jpanMineField.add(c, new AbsoluteConstraints(p.x * getCellSize() + 5, p.y * getCellSize() + 5, -1, -1));
            c.setVisible(true);
        });
        
        this.revalidate();
    }
    
    private void setInitialCellAtributes(Cell cell) {
        cell.setPreferredSize(new Dimension(getCellSize(), getCellSize()));
        cell.setFocusable(false);
        cell.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        cell.setFocusable(false);
        cell.addMouseListener(new CellAdapter());
    }

    private void clearBoard() {
        jpanMineField.removeAll();
        jpanMineField.updateUI();
    }
    
    public void showAllMines() {
        getBoardMap().showAllMines();
        if (showConfirmationMessage(languages.getString("MINESTEPPED"), null)) {
            novoJogo();
        }
    }

    private void loadMines(int hPos, int vPos) {
        // Colocando as minas, sempre testando que todas tenham sua célula
        int minesLeft = _minesQty, i, j;
        Point aux = new Point();
        ArrayList<Point> positions = getBoardMap().get(new Point(hPos, vPos)).getPerimeter().getPerimeterPositions();
        positions.add(new Point(hPos, vPos)); // adding cell's own position
        for (; minesLeft > 0;) {
            do {
                i = (int) (Math.random() * (getNRows()));
                j = (int) (Math.random() * (getNCols()));
                aux.setLocation(i, j);
            } while (positions.contains(aux));
            // Por BoardMap
            if (!boardMap.get(aux).isMine()) {
                getBoardMap().get(aux).setMine();
                getBoardMap().get(aux).increasePerimeterNumbers();
                minesLeft--;
            }
        }
    }

    private void restartMines() {
        remainingMines = _minesQty;
//        jlabMinas.setText(MENSAGEM_MINAS + String.valueOf(_minesQty));
        jlabMinas.setText(MENSAGEM_MINAS + _minesQty);
    }

    public boolean showConfirmationMessage(String title, String message) {
        return (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(
                this, 
                (message == null) ? languages.getString("START_NEW") : message, 
                title, 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE));
    }

    private void restartGoldCoins() {
        goldCoins = 0;
        successfulGuesses = 0;
        showGoldCoins();
    }

    private void loadConfigForm() {
        configForm.setVisible(true);
    }

    public int getMinesQty() {
        return _minesQty;
    }

    public void setMinesQty(int _minesQty) {
        this._minesQty = _minesQty;
    }

    private void initPreferences() {
        _minesQty = configForm.getPreferenceFromIni(Configuration.Prefs.MINES_QTY_EXPERT);
        _nRows = configForm.getPreferenceFromIni(Configuration.Prefs.N_ROWS_EXPERT);
        _nCols = configForm.getPreferenceFromIni(Configuration.Prefs.N_COLS_EXPERT);
        _cellSize = configForm.getPreferenceFromIni(Configuration.Prefs.CELL_SIZE_DEFAULT);
        _pointCost = configForm.getPreferenceFromIni(Configuration.Prefs.POINTS_COST_EXPERT);
    }

    protected class CellAdapter extends MouseAdapter  {

        @Override
        public void mousePressed(MouseEvent e) {
            boolean clickProcessed = false;
            if (!isGameOver()) {
                Cell cell = (Cell) e.getSource();
                
                // Revela perímetro
                // Se forem os dois ao mesmo tempo
                int bothMask = MouseEvent.BUTTON1_DOWN_MASK | MouseEvent.BUTTON3_DOWN_MASK;
                if ((e.getModifiersEx() & bothMask) == bothMask || SwingUtilities.isMiddleMouseButton(e)) {
                    clickProcessed = true;
                    if (cell.isUncovered() && cell.isNumbered()) {
                        if (!cell.revealPerimeter()) {
                            setGameOver(true);
                            setFirstClick(true);
                            showAllMines();
                        }
                    }
                }
                
                // Dica do número
                // Se for o do meio
                if (SwingUtilities.isMiddleMouseButton(e)) {
                    // Dica
                    if (cell.isUncovered() && cell.isNumbered()) {
                        if (goldCoins >= getPointCost() && 
                                showConfirmationMessage(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("resources/languages")
                                        .getString("COINS_USED"), new Object[] {String.valueOf(getPointCost())}) , languages.getString("SHOW_MINE"))) {
                            cell.pointMine();
                            setRemainingMines(true);
                            addGoldCoins(-getPointCost());
                        }
                    }
                }

                // Marcação de célula
                // Se foi apenas o direito
                if (SwingUtilities.isRightMouseButton(e)) {
                    if (!clickProcessed){
                        clickProcessed = true;
                        Cell.Marks lastMark = cell.toggleMark();
                        if (!cell.isUncovered() && lastMark == Cell.Marks.COVERED && cell.isFlagMarked()) {
                            setRemainingMines(true);
                            if (cell.isMine()) 
                                addSuccesfulGuess(1);
                        }
                        else if (!cell.isUncovered() && lastMark == Cell.Marks.MINEFLAG) {
                            setRemainingMines(false);
                            if (cell.isMine()) 
                                addSuccesfulGuess(-1);
                        }
                    }
                } 

                // Revelação de célula
                // Se foi apenas o esquerdo
                if (SwingUtilities.isLeftMouseButton(e)) {
                    if (!clickProcessed) {
                        if (isFirstClick()) {
                            loadMines(cell.getHPos(), cell.getVPos());
                            relogio.iniciar();
                            setFirstClick(false);
                            setGameStarted(true);
                        }
                        if (!cell.reveal()){
                            setGameOver(true);
                            setFirstClick(true);
                            showAllMines();
                        }
                    } 
                }
            }
        }
    }
    
    protected class BoardMap extends HashMap<Point, Cell>{
        
        /**
         * Filter all cells with mines than check if every each one of them
         * is flag marked.
         * @return true if all of them are. false otherwise.
         */
        public boolean areAllMinesFlagged() {
            Iterator<Cell> cells = values().stream().filter(c -> c.isMine()).iterator();
            Cell minedCell;
            
            while(cells.hasNext()) {
                minedCell = cells.next();
                if (!minedCell.isFlagMarked()) {
                    return false;
                }
            }
            
            return true;
        }
        
        public long remainingCoveredCells() {
            return values().stream().filter(c -> c.isCovered()).count();
        } 
        
        public void showAllMines() {
            values().stream().filter(c -> c.isMine() || c.isFlagMarked()).forEach(c -> {
                c.showMine();
            });
        }
        
        public void revealAllCells() {
            values().stream().filter(c -> !c.isMine() && !c.isUncovered()).forEach(c -> {
                c.reveal();
            });
        }
        
        public void flagRemainingCells() {
            Stream<Cell> covered = values().stream().filter(c -> c.isCovered());
            if (covered.count() == remainingMines) {
                covered.forEach(c -> c.toggleMark());
            }
        }
        
//        public void flagObviousCells() {
//            // Primeiro, separam-se as celulas numeradas e descobertas
//            values().stream().filter(c -> c.isNumbered() && c.isUncovered()).forEach(c -> {
//                // Se a contagem de celulas cobertas do perímetro é igual ao número da célula
//                if (c.getPerimeter().stream().filter(neighbor -> neighbor.getMark().equals(Cell.Marks.COVERED)).count() == c.getNumber()) {
//                    // Aciona todas as células do perímetro
//                    c.getPerimeter().forEach(neighbor -> neighbor.toggleMark());
//                }
//            });
//        }
    }

    /**
     * @return the _nRows
     */
    public  int getNRows() {
        return _nRows;
    }

    /**
     * @param anRows the _nRows to set
     */
    public  void setNRows(int anRows) {
        _nRows = anRows;
    }

    /**
     * @return the _nCols
     */
    public  int getNCols() {
        return _nCols;
    }

    /**
     * @param anCols the _nCols to set
     */
    public  void setNCols(int anCols) {
        _nCols = anCols;
    }

    /**
     * @return the _cellSize
     */
    public  int getCellSize() {
        return _cellSize;
    }

    /**
     * @param aCellSize the _cellSize to set
     */
    public  void setCellSize(int aCellSize) {
        _cellSize = aCellSize;
    }
    
    public final class WindowLayoutEvent extends WindowEvent {
        
        public WindowLayoutEvent(Window source, int id) {
            super(source, id);
        }
        
    }
    
    public interface WindowResizeListener {
        public abstract void windowResized(WindowEvent we);
    }
}
